development:
  adapter: postgresql
  encoding: unicode
  database: kuljakke
  host: localhost
  pool: 5
  username: circon
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: kuljakke_test
  host: localhost
  pool: 5
  username: circon
  password: password
