development:
  adapter: postgresql
  encoding: unicode
  database: tkk
  host: localhost
  pool: 5
  username: circon
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: tkk_test
  host: localhost
  pool: 5
  username: circon
  password: password
